### ISSUE TITLE
How to insert empty polygon to geography column

### ISSUE THREAD

**Issue by palhal** [NetTopologySuite/NetTopologySuite#588] opened 2022-02-02 16:17 UTC
### Prerequisites
- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of NetTopologySuite
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Before inserting a polygon into a geography column, NTS checks that IsCCW is true. I want to insert an empty polygon, but haven't found a way to create one with IsCCW set to true. Perhaps NTS should not check the orientation for empty geometries? I am able to insert an empty polygon using raw SQL.

### Steps to Reproduce
Approach 1:
```csharp
var factory = NtsGeometryServices.Instance.CreateGeometryFactory(srid: 4326);
var ring = factory.CreateLinearRing();

if (!ring.IsCCW)
{
    ring = (LinearRing)((Geometry)ring).Reverse();
}

var polygon = factory.CreatePolygon(ring);
Console.WriteLine(ring.IsCCW); // False
Console.WriteLine(polygon.Shell.IsCCW); // False
```

Approach 2:
```csharp
var factory = new GeometryFactoryEx(new PrecisionModel(), srid: 4326)
{
    OrientationOfExteriorRing = LinearRingOrientation.CounterClockwise
};

var polygon = factory.CreatePolygon();
Console.WriteLine(polygon.Shell.IsCCW); // False
```

Needless to say, both approaches result in the same error:
_System.ArgumentException : When writing a SQL Server geography value, the shell of a polygon must be oriented counter-clockwise._

### System Configuration
Tell us about the environment where you are experiencing the bug:
- NetTopologySuite version: 2.3.0
- Other NetTopologySuite packages and versions: Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite 6.0.1
- Environment (Operating system, version and so on): Windows 10, MS SQL 15
- .NET version: 6.0

**Comment by FObermaier** [comment] 2022-02-02 19:52
This is a duplicate of https://github.com/NetTopologySuite/NetTopologySuite.IO.SqlServerBytes/issues/14

**Comment by palhal** [comment] 2022-02-02 20:20
Oh, I'm sorry. I'm not too familiar with NTS and its modules yet. I couldn't find that issue by googling either. Feel free to close this.

**Closed** 2022-02-03 07:43 UTC
