### ISSUE TITLE
Difference between .Distance (EF Core) and .Distance (local C#)

### ISSUE THREAD

**Issue by rudiv** [NetTopologySuite/NetTopologySuite#441] opened 2020-10-22 10:39 UTC
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of NetTopologySuite
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When calling .Distance on 2 points, the result is different depending on whether the method is called via EF Core (as part of a LINQ Query) or when calling it directly on 2 points retrieved from the database locally in C#.

### Steps to Reproduce
Using this code, different results are seen between `result` and `badResult`:
```
var geometryFactory = NtsGeometryServices.Instance.CreateGeometryFactory(srid: 4326);
var point = geometryFactory.CreatePoint(new Coordinate(scan.Longitude, scan.Latitude));

var result = dbContext.Locations.Select(m => new { Distance = m.Location.Distance(point) }); // Correct, in meters
var testPointFromDb = dbContext.Locations.First(m => m.Location);
var badResult = testPointFromDb.Distance(point); // Incorrect, seems to be overall distance between coordinates
```

### System Configuration
Tell us about the environment where you are experiencing the bug:
- Other NetTopologySuite packages and versions: Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite 3.18
- Environment (Operating system, version and so on): Windows 10 19041.508
- .NET Framework version: .NET Core 3.1.8
- Additional information: N/A

**Comment by airbreather** [comment] 2020-10-22 11:56
Duplicate of #233

**Closed by airbreather** 2020-10-22 11:56 UTC
Labels: bug, duplicate
