### ISSUE TITLE
.NET Core no ShapefileReader and ShapefileDataReader

### ISSUE THREAD

**Issue by thinking-aloud** [NetTopologySuite/NetTopologySuite#187] opened 2017-08-23 08:06 UTC
Thanks to @airbreather (#110 #183) NTS can be installed with NuGet in .NET Core.

I tried version 1.15.0-pre013 and realized inside NetTopologySuite.IO there is no **ShapefileReader** and **ShapefileDataReader**.
I have the same code with the same Nuget packets inside Mono and it works fine.

**Comment by airbreather** [comment] 2017-08-23 10:56
Duplicate of #184 (see the second checkbox on that one).

**Closed by airbreather** 2017-08-23 10:56 UTC
