### ISSUE TITLE
Add instead of AddAttribue

### ISSUE THREAD

**Issue by HarelM** [NetTopologySuite/NetTopologySuite#185] opened 2017-08-22 21:03 UTC
I know this package follows the JTS code but the following change would be very useful, even as another method to `AttributesTable`:
`Add` method instead or as addition to `AddAttribute`
This will facilitate for the following code using .Net (No need to do anything special besides adding the above method):
`var attributesTable = new AttributesTable {{"highway", highwayType}};`
Which is better, IMO, than:
```
var attributesTable = new AttributesTable();
attributesTable.AddAttribute("highway", highwayType);
```
I'm pretty sure I wrote it sometime ago, but I can't find it...

**Comment by FObermaier** [comment] 2017-08-23 06:15
Here you go:
https://github.com/NetTopologySuite/NetTopologySuite/blob/Refactor_for_NETStandard/NetTopologySuite/Features/AttributesTable.cs

**Comment by FObermaier** [comment] 2017-08-23 06:26
Duplicate of #130

**Closed** 2017-08-23 06:26 UTC

**Comment by HarelM** [comment] 2017-08-23 07:13
I knew I already opened it :-) 
But it not in the latest pre-release for some reason...?
I updated my reference yesterday and it stopped working...?

**Comment by HarelM** [comment] 2017-08-26 07:38
Please reopen this issue as this was left out of the latest .net core release...

**Comment by airbreather** [comment] 2017-08-26 10:37
Didn't 4ea0698 make it into the latest auto-built NuGet package?

**Comment by HarelM** [comment] 2017-09-12 15:09
I'm guessing the following release has this functionality (I hope):
https://www.nuget.org/packages/NetTopologySuite/1.15.0-pre017
Where can I find some release notes?
Also any reason why this isn't an official release instead of a pre-release?
