### ISSUE TITLE
Valid geojson cannot be parsed.

### ISSUE THREAD

**Issue by xivk** [NetTopologySuite/NetTopologySuite#176] opened 2017-07-19 10:02 UTC
This perfectly valid geosjon cannot be parsed:

https://github.com/oSoc17/rideaway-data/blob/master/src/data/gfr/11b.geojson

There are 2 TODO's here:

- [x]  Fix the immidiate issue.
- [ ] Have a look at the GeoJSON code, it's unverified to handle the geosjon spec.

**Comment by DGuidi** [comment] 2017-08-17 17:06
still failing, right?

**Comment by xivk** [comment] 2017-08-17 17:07
Yes, waiting for the .NET Core thing to happen first ;-)

**Comment by DGuidi** [comment] 2017-08-17 17:08
I see that in airbreather:squashed test fails

**Comment by xivk** [comment] 2017-08-17 17:09
Oh that's probably because I fixed it after?

**Comment by DGuidi** [comment] 2017-08-17 17:11
code in "squashed branch" looks aligned with your changes.

**Comment by airbreather** [comment] 2017-08-18 02:45
`GeoJsonDeserializeIssue176` fails on my machine, both on my `squashed` branch and the latest `develop` branch:

```
Test Name:	GeoJsonDeserializeIssue176
Test FullName:	NetTopologySuite.IO.Tests.GeoJSON.GeoJsonSerializerTest.GeoJsonDeserializeIssue176
Test Source:	C:\Users\joe\src\NetTopologySuite\NetTopologySuite.IO\NetTopologySuite.IO.Tests\GeoJSON\GeoJsonSerializerTest.cs : line 106
Test Outcome:	Failed
Test Duration:	0:00:00.122

Result StackTrace:	
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
at NetTopologySuite.IO.Tests.GeoJSON.GeoJsonSerializerTest.GeoJsonDeserializeIssue176() in C:\Users\joe\src\NetTopologySuite\NetTopologySuite.IO\NetTopologySuite.IO.Tests\GeoJSON\GeoJsonSerializerTest.cs:line 112
Result Message:	Newtonsoft.Json.JsonSerializationException : Could not create an instance of type NetTopologySuite.Features.IFeature. Type is an interface or abstract class and cannot be instantiated. Path 'features[0].geometry', line 1, position 55.
```

**Comment by xivk** [comment] 2017-08-18 08:58
I don't know why but I'm unable to run the tests. I have no way to check what's going wrong at the moment, looks like we are going to have to put this on hold **again**.

What is going on with this project, it seems to be cursed, have been trying to get .NET Core support done for over a year now. 

Can someone please look at why the tests aren't working? I have the lastest VS2017 setup, or tell me how you are running the tests.

**Comment by DGuidi** [comment] 2017-08-18 08:58
I've fixed this: commit soon

**Comment by xivk** [comment] 2017-08-18 09:00
How are you running the tests? No idea why this isn't working for me.

**Comment by DGuidi** [comment] 2017-08-18 09:03
I'm working in standard develop branch using resharper. plain old VS2017 test explorer looks not working also for me.

**Comment by xivk** [comment] 2017-08-18 09:07
Ok, thanks for the feedback and for fix this, I'm creating a new issue for this later. 👍

**Comment by DGuidi** [comment] 2017-08-18 09:11
@xivk can you please take a look at my commit? I've added [this](https://github.com/NetTopologySuite/NetTopologySuite/commit/ab28cce516b0a8d2c272eb58d8922f45e699d2ca#diff-539b341dc3aed9dcd0eed06450bfd9c6R14) because standard `JsonSerializer.Create` is the cause of the broken behavior

**Comment by xivk** [comment] 2017-08-18 09:20
Look good to me. Not sure why this is failing, I used JsonSerializer.Create because the constructor is declared Obsolete, not sure why that is either.

**Comment by DGuidi** [comment] 2017-08-18 09:34
feel free to close this issue if all looks good to you

**Comment by xivk** [comment] 2017-08-18 09:36
There is still the issue of reviewing the code in general of the GeoJSON IO package so not closing yet, but I consider this fine for now.

**Comment by airbreather** [comment] 2017-08-18 10:18
> Can someone please look at why the tests aren't working? I have the lastest VS2017 setup, or tell me how you are running the tests.

> How are you running the tests? No idea why this isn't working for me.

> I'm working in standard develop branch using resharper. plain old VS2017 test explorer looks not working also for me.

VS2017 test explorer is working for me, I just needed to install this extension:
![image](https://user-images.githubusercontent.com/3792815/29454888-ed53aa16-83dc-11e7-8cfe-e53f5b321c11.png)

**Comment by xivk** [comment] 2017-08-18 10:59
Ok, thanks, will try, I had the latest NUnit test explorer, that's probably why. Perhaps we should also look into upgrading to the latest NUnit version later.

**Comment by airbreather** [comment] 2017-08-20 01:32
The link above is broken.

https://github.com/oSoc17/rideaway-data/blob/47bcc37b87727e5f8ee14e1e6b1ce5a2fa2d88ea/src/data/gfr/11b.geojson

**Comment by FObermaier** [comment] 2018-02-20 12:32
@xivk, the mentioned test passes on my machine. could you please verify.
What do we have to do to "certify" our GeoJSON serializers?

**Comment by xivk** [comment] 2018-02-20 13:41
If I remember correctly it means adding more test cases to make sure we fully support the entire geojson spec. I ran into a few issues and they are fixed but there is no guarantee the full spec is supported.  If I remember correctly, this has been a while...

Related, I recently had this one:

https://github.com/NetTopologySuite/NetTopologySuite.IO.GeoJSON/issues/1

Also, if we still agree on #191 I'm willing to continue the work, it's mostly done anyway.

**Comment by FObermaier** [comment] 2018-02-20 14:04
Ok, I'll close this issue, and we can open another one for the certification over at the [GeoJSON](/NetTopologySuite/NetTopologySuite.IO.GeoJSON) repository.

**Closed by FObermaier** 2018-02-20 14:04 UTC
Labels: bug
