### ISSUE TITLE
Create an officially released version

### ISSUE THREAD

**Issue by HarelM** [NetTopologySuite/NetTopologySuite#206] opened 2017-12-12 22:47 UTC
I believe it's time to create an officially released version, pre-release is exiting for far to long, don't you think? :-)

**Comment by MuhKuh7** [comment] 2018-02-15 09:55
Yes, I would appreciate that as well ;)

**Comment by pauldendulk** [comment] 2018-02-19 09:18
What needs to be done before it can be released?

**Comment by FObermaier** [comment] 2018-02-19 09:38
We aim to be in sync with JTS, both in functionality and version, meaning when you pick NTS 1.14, you get the same functionality as JTS 1.14.   

JTS 1.15 has been released late 2017, NTS has not yet the same functionality. I'm working on it. Unfortunatly (in terms of release) there have been several breaking changes that prevent us from releasing intermediate 1.14.1. Additionally there will be more breaking-changes, even to GeoAPI prior to the release of NTS 1.15.

The pre-release version [pre-36](https://www.nuget.org/packages/NetTopologySuite/1.15.0-pre036) would be my current choice.

**Comment by roji** [comment] 2018-02-21 06:01
@FObermaier, is there any estimate on when 1.15 will be coming out? The current lack of netstandard support in particular is problematic...

**Comment by FObermaier** [comment] 2018-02-21 10:38
@roji, most likely not before easter.

**Comment by FObermaier** [comment] 2018-03-02 07:35
If I havn't missed anything we are now at JTS version 1.15.
Could you please try https://www.nuget.org/packages/NetTopologySuite/1.15.0-pre061

There has been a regression in the JTS' codebase (https://github.com/locationtech/jts/issues/265) which I'm tempted to fix before the release of NTS 1.15.

**Comment by roji** [comment] 2018-04-08 08:49
@FObermaier any more info on a release date? The entire .NET Core ecosystem is about to release preview2, and NetTopologySuite is currently critical to supporting PostgreSQL in Npgsql and EF Core. I really appreciate the work you guys are doing (and I know what it's like to maintain an open source project on the side), I really hope you can release 1.15 before .NET Core 2.1 RTMs...

**Comment by wboevink** [comment] 2018-05-14 15:17
@FObermaier I was wondering if there's any news on a release date?

**Comment by Diaaz** [comment] 2018-07-11 13:06
@FObermaier Is there any news on a release date? We are using NetTopologySuite in all of our projects and are starting to use Postgres. The Postgres Npgsql driver uses NetTopopogySuite 1.15, which is still in preview. Result is we have to update all references to the preview version of NTS.

**Comment by roji** [comment] 2018-07-13 06:07
I can see that GeoAPI was released on nuget.org a couple days ago, does that mean we can expect NTS to be released as well in the very near future? Would be useful to know in order to react appropriately...

**Comment by FObermaier** [comment] 2018-07-13 06:12
@roji , could you and @YohDeadfall "sign" CLA (https://github.com/NetTopologySuite/NetTopologySuite/pull/249) and we are ready to go.

**Comment by roji** [comment] 2018-07-13 06:58
@FObermaier, we both signed - I think it's good to go.

(just as a reminder, we also will need https://github.com/NetTopologySuite/NetTopologySuite.IO.PostGis/pull/2 to be merged and that package to be released at some point, although that's not blocking this release).

**Comment by FObermaier** [comment] 2018-07-13 10:57
Thanks for the patience with me, this is finally done.

**Closed by FObermaier** 2018-07-13 10:57 UTC

**Comment by roji** [comment] 2018-07-13 11:55
Great news, thanks!

Can you please clarify the status of NetTopologySuite.IO, which the Npgsql driver depends on? I can only see 1.15.0 prerelease version on nuget, is that package supposed to be released as well or has it been replaced by another package? I can also see a NetTopologySuite.IO.PostGis that hasn't been updated since 2014, you may considering delisting it (and other obsolete packages) to make sure users don't install the wrong thing.
