### ISSUE TITLE
Add UseNetTopologySuite for EF InMemoryDatabase

### ISSUE THREAD

**Issue by Frigik** [NetTopologySuite/NetTopologySuite#400] opened 2020-04-20 09:47 UTC
I have setup NetTopologySuit with EntityFramework core.
Here is my startup setup.
`  services.AddDbContextPool<EFContext>((provider, options) =>
                options                
                    .UseSqlServer(provider.GetService<IConfiguration>().GetConnectionString("Database"), sqlOptions =>
                    {                        
                        sqlOptions.UseNetTopologySuite();                      
                    })`
I'm using distance calculation feature.  When I'm using it with real SQL database it is working fine. e.g.
`query.Where(s => s.Location.Distance(startingLocation) < radius)`

But when it comes to tests, the line above not working properly. I'm using Microsoft.EntityFrameworkCore.InMemory package. Can you please add support of InMemoryEntityFrameworkCore ?

Something like
` services
                    .AddDbContext<DbContext>(options =>
                    {
                        options.UseInMemoryDatabase(
                            Guid.NewGuid().ToString(), 
                            opts => opts.UseNetTopologySuite() //pseudocode line
                        );

                    })`

**Comment by airbreather** [comment] 2020-04-20 10:53
Duplicate of #233 I think?

**Comment by airbreather** [comment] 2020-04-28 12:53
Closing as duplicate.

**Closed by airbreather** 2020-04-28 12:53 UTC
Labels: bug, duplicate
