### ISSUE TITLE
Incorrect Distance Calculation

### ISSUE THREAD

**Issue by nssidhu** [NetTopologySuite/NetTopologySuite#450] opened 2020-11-21 06:10 UTC
I am using .NET core.
Trying to do simple calculation between two point and not getting anywhere close the the expected result.
Am i missing anything??
I plan to use this with Entity FrameCore .net 5
```
          var point1 = new NetTopologySuite.Geometries.Point(41.87587, -87.61906) { SRID = 4326 }; //Chicago
            var point2 = new NetTopologySuite.Geometries.Point(42.27096, -89.09375) { SRID = 4326 }; //RockFord, IL
            var dist1 = point2.Distance(point1);

            var point3 = new NetTopologySuite.Geometries.Point( -87.61906, 41.87587) { SRID = 4326 }; //Chicago
            var point4 = new NetTopologySuite.Geometries.Point(-89.09375, 42.27096) { SRID = 4326 }; //RockFord, IL
            var dist2= point4.Distance(point3);

            //Expected Distance 80.42 mi or (129.42 km) as per google maps, coordinates were taken from google Map
            Console.WriteLine("Done");
```

![image](https://user-images.githubusercontent.com/3267605/99869044-a5625480-2b8d-11eb-83e8-67265c243ec9.png)

**Comment by DGuidi** [comment] 2020-11-21 09:09
Distance are calculated in the unit you specified so I'm your case in degrees and not meters. You should do the conversion by yourself.
Keep also in mind that the algorithms are planar so distances obtained with nts using degrees are valid probably only for small distances.

**Comment by airbreather** [comment] 2020-11-21 10:46
Duplicate of #233.

> I plan to use this with Entity FrameCore .net 5

The calculation should work just fine when you use EF Core to run it on the database side.

**Closed** 2020-11-21 10:47 UTC

**Comment by nssidhu** [comment] 2020-11-21 14:33
Can I not directly get them calculated in meters without doing conversions when using NTS library ?
What settings would help me get distance in meters if possible ?



Sent from Yahoo Mail for iPhone


On Saturday, November 21, 2020, 3:10 AM, Diego Guidi <notifications@github.com> wrote:




Distance are calculated in the unit you specified so I'm your case in degrees and not meters. You should do the conversion by yourself.
Keep also in mind that the algorithms are planar so distances obtained with nts using degrees are valid probably only for small distances.

**Comment by DGuidi** [comment] 2020-11-23 07:44
@nssidhu please check [this comment](https://github.com/NetTopologySuite/NetTopologySuite/issues/443#issuecomment-716366691) from issue #443 , maybe can be helpful to you
