### ISSUE TITLE
Crash in Operation\Polygonize\PolygonizeGraph.cs 

### ISSUE THREAD

**Issue by ohagenes** [NetTopologySuite/NetTopologySuite#146] opened 2017-01-10 09:48 UTC
The method public void AddEdge(ILineString line) crashes with "System.IndexOutOfRangeException: Index was outside the bounds of the array" when fed short segments that lie too close since

     Coordinate[] linePts = CoordinateArrays.RemoveRepeatedPoints(line.Coordinates);

reduces to a single point. Shall I precondition the input data to avoid it or is it serious enough to make it into the suite? I guess the following is a "fix" of the crash:

   if (linePts.Length < 2)
      return;

**Comment by DGuidi** [comment] 2017-01-14 10:00
looks a duplicate of #87 
code already fixed in master

**Closed by DGuidi** 2017-01-14 10:00 UTC

**Comment by ohagenes** [comment] 2017-01-14 11:25
Thank you for the swift action.
